userContext issue done
HackYourFuture-CPH/web-dev-rooms pull request #165
Opened 2020-12-09 20:44 UTC by MaherHussain

# Description

PR is about userContext that save data local storage when user log in and remove the data from  local storage when the user log out , it made by Maher and Nuha .

Fixes #97

# How to test?

we have created a Router in App.js called "/usertest" and all work fine ?

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

2020-12-10 09:20 UTC, bytewiz requested changes
Seems correct, but it only wraps one route. Usually, you would wrap the entire app in the context provider so you can access the context in the entire app. At least that is usually the case for Auth-related context as we need to check it etc.

2020-12-10 09:20 UTC, bytewiz commented on src/client/context/userContext.js
> +    /* alert("token will delete") */
you can remove this commented out line

2020-12-10 09:20 UTC, bytewiz commented on src/client/context/userContext.js
> +    console.log('login');
Remove `console.log()`

2020-12-11 16:54 UTC, yukafjaponesa reviewed
when bytewiz's feedback implemented, then looks good.

2020-12-13 10:45 UTC, tpetrina requested changes
Please address all comments.

2020-12-13 10:45 UTC, tpetrina commented on src/client/context/UserContextTest.js
> +    <UserProvider>
You don't need UserProvider here.

2020-12-13 10:45 UTC, tpetrina commented on src/client/context/UserContextTest.js
> +export default AppWithStore;
You are importing this as `UserTest` in `App.js`, keep names the same.

2020-12-13 14:40 UTC, tpetrina submitted a review, later dismissed
Fix conflict and you are good to go!

2020-12-14 07:35 UTC, tpetrina submitted a review, later dismissed
Good stuff!

2020-12-14 08:23 UTC, Pallabi-ghosh submitted a review, later dismissed

2020-12-14 13:33 UTC, Yaser-Aldammad submitted a review, later dismissed

2020-12-14 20:40 UTC, tpetrina submitted a review, later dismissed

2020-12-14 21:53 UTC, Elia-Git approved these changes
Good job!

2020-12-14 23:32 UTC, dpfernandes approved these changes
👍

2020-12-14 23:32 UTC, merged