AppHeader CSS improvement
HackYourFuture-CPH/web-dev-rooms pull request #166
Opened 2020-12-09 22:30 UTC by Yaser-Aldammad

# Description

improved CSS for AppHeader to be more flexible and clearer

Fixes # (issue)

# How to test?

tested by storybook
# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2020-12-10 09:21 UTC, bytewiz requested changes
I don't see any linked issue, please link the issue that this pull request solves

2020-12-10 09:44 UTC, Yaser-Aldammad commented
there is no issue to this branch except improving a previous component which makes things easier for others to use

2020-12-10 14:30 UTC, MaherHussain submitted a review, later dismissed

2020-12-13 10:47 UTC, tpetrina submitted a review, later dismissed

2020-12-13 13:27 UTC, tpetrina approved these changes

2020-12-13 14:37 UTC, MaherHussain approved these changes

2020-12-14 19:22 UTC, tpetrina approved these changes

2020-12-14 20:52 UTC, MaherHussain approved these changes

2020-12-14 23:13 UTC, merged