API:endpoint to write the feedback for each event participation-student
HackYourFuture-CPH/web-dev-rooms pull request #168
Opened 2020-12-10 12:55 UTC by AkoAyukngat

# Description
This issue will help users(students) to post feedbacks regarding the events they participated in. Though I have some views I will like us to look into if necessary.

1. I tried inserting the 'mentor-id' & 'title' to the feedback body but it gave an error,  'unknown column: title/mentor-id in field list'
    I think these columns should be added on the feedback table if there is a necessity; to avoid this error when the above is 
    included in the feedback body.

Fixes # (issue)

# How to test?

Swagger can be used to test this issue

# Checklist

- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2020-12-11 19:33 UTC, claudion3 commented
Nice work, but what happen with that big block of comment?

2020-12-12 06:00 UTC, AnilMula commented
Good work! 

A suggestion.

merge the latest develop into branch. and post request in api-router.js

2020-12-13 11:24 UTC, AkoAyukngat commented
> Nice work, but what happen with that big block of comment?

Its just an explanation of my experiences when fixing the issue, so the mentors/reviewers already know what I experienced.

2020-12-13 13:25 UTC, tpetrina reviewed
Good start, but just need fixing small things.

2020-12-13 13:25 UTC, tpetrina commented on src/server/api/routes/feedbacks.router.js
> +  console.log('feedback posted');
Remove `console.log`.

2020-12-13 13:25 UTC, tpetrina commented on src/server/api/routes/feedbacks.router.js
> +      console.log(error);
Remove `console.log`.

2020-12-13 13:25 UTC, tpetrina commented on src/server/api/controllers/feedbacks.controller.js
> +    answered_by: body.answered_by,
Remove `answered_by` from here - it will be done through a different endpoint.

2020-12-13 13:25 UTC, tpetrina commented on src/server/api/controllers/feedbacks.controller.js
> +    description: body.description,
Properties coming from JSON don't have `_` in them.
`student_id` should be `studentId` when in body.

2020-12-14 22:18 UTC, Elia-Git reviewed
Would love to see the previous feedback implemented.

2020-12-14 22:25 UTC, Elia-Git reviewed
Don't forget to use the latest DB-diagram version ..https://dbdiagram.io/d/5fb801913a78976d7b7cc7d8

2020-12-22 19:23 UTC, tpetrina requested changes
Almost done, minor changes requested.

2020-12-22 19:23 UTC, tpetrina commented on src/server/api/controllers/feedbacks.controller.js
> +// const moment = require('moment-timezone');
Remove commented code.

2020-12-22 19:23 UTC, tpetrina commented on src/server/app.js
> +// If "/api" is called, redirect to the API documentation.
Remove comment. This file should not be changed in your PR. Use `git restore src/server/app.js` to reset it.

2020-12-24 09:42 UTC, tpetrina approved these changes
Looks good, ship it!

2020-12-24 10:46 UTC, nuha90 approved these changes

2020-12-24 10:46 UTC, merged