Added react-testify and an example Test button with onClick action
HackYourFuture-CPH/web-dev-rooms pull request #169
Opened 2020-12-10 20:41 UTC by AnilMula

# Description

Added support for toasts with react-toastify. And created a button that triggers a message.

Fixes #164 

# How to test?

Tested in the local system

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality
![react toastify](https://user-images.githubusercontent.com/60918335/101827283-67bf6e80-3b30-11eb-8a04-d77e047ae36f.gif)

2020-12-12 16:23 UTC, tpetrina requested changes
Good start, but a bit too simplistic.

2020-12-12 16:23 UTC, tpetrina commented on src/client/components/ReactToastify/Button/Button.js
> +      <ToastContainer />
This should go to `App.js`.

2020-12-12 16:23 UTC, tpetrina commented on src/client/components/ReactToastify/Button/Button.js
> +import 'react-toastify/dist/ReactToastify.css';
This should go to `App.js`.

2020-12-12 16:23 UTC, tpetrina commented on src/client/containers/Home/Home.js
> +    <Button />
Just add the toast part here, no need to introduce a component just for testing stuff since it will be deleted anyway.

2020-12-13 07:43 UTC, AnilMula commented
adjusted as suggested

2020-12-13 10:47 UTC, tpetrina approved these changes

2020-12-13 12:10 UTC, Deepti-Dk approved these changes

2020-12-13 12:10 UTC, merged