Modal View Cancelation/Deletion of Mentor's event registration
HackYourFuture-CPH/web-dev-rooms pull request #174
Opened 2020-12-12 11:07 UTC by 1620prabn

# modal view for cancelation/deletion of mentor's event registration 

Please provide a short summary explaining what this PR is about.

Fixes # (#141 )

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

2020-12-13 13:22 UTC, tpetrina requested changes
Good start, just a little bit more.

2020-12-13 13:22 UTC, tpetrina commented on src/client/components/ModalWithCancelRegistration/ModalWithCancelRegistration.js
> +          <Button>Cancel</Button>
Propagate `onClick` through props as well.

2020-12-14 19:32 UTC, tpetrina commented on src/client/components/ModalWithCancelRegistration/ModalWithCancelRegistration.css
> +.cancel-reg-modal .modal-wrapper {
Isn't this too much CSS when the base Modal is good enough?

2020-12-16 08:00 UTC, tpetrina approved these changes
Nice.

2020-12-17 16:14 UTC, MaherHussain approved these changes

2020-12-17 18:50 UTC, merged