specific event details modal view
HackYourFuture-CPH/web-dev-rooms pull request #175
Opened 2020-12-13 09:08 UTC by MaherHussain

# Description

PR is about creating a modal view for specific event details and some changes in other components .

Fixes #129 

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

2020-12-13 13:21 UTC, tpetrina requested changes

2020-12-13 13:21 UTC, tpetrina commented on src/server/api/routes/api-router.js
> -
This file shouldn't appear in your PR.

2020-12-13 13:21 UTC, tpetrina commented on src/client/containers/Admin-Event-details/Admin-Event-modal-view.js
> +              link="www.hyf.org"
You cannot hard-code these here since these depend on what your event actually contains. They should come through props.

2020-12-13 13:21 UTC, tpetrina commented on src/client/containers/Admin-Event-details/Admin-Event-modal-view.js
> +              DemoStudent1|class15 <span className="close-btn">x</span>
All of this data below should be coming from props, not be hard-coded here.

2020-12-15 06:07 UTC, closed without merging

2020-12-15 06:08 UTC, MaherHussain commented
closing PR