API: Create an Event
HackYourFuture-CPH/web-dev-rooms pull request #185
Opened 2020-12-14 18:19 UTC by Deepti-Dk

# Description

This PR is to create an event with FK constraints working. I have updated existing 'events.router.js' and 'events.controller.js' with POST to create an event.

Fixes #133 

# How to test?

tested on swagger and postman

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

2020-12-14 19:35 UTC, tpetrina requested changes
The backend code looks neat and tidy, but there are other files in the frontend and I don't know what to do with them? Can you please separate them into another PR so that this one goes in smoothly?

2020-12-14 19:35 UTC, tpetrina commented on src/server/api/routes/api-router.js
> +
Undo change in this file.

2020-12-16 07:47 UTC, tpetrina approved these changes
Please cleanup before you merge.

2020-12-16 07:47 UTC, tpetrina commented on src/server/api/routes/api-router.js
> +// const createEventRouter = require('./create-event.router');
Remove commented code.

2020-12-16 07:47 UTC, tpetrina commented on src/server/api/routes/api-router.js
> +// router.use('/createEvent', createEventRouter);
Remove commented code.

2020-12-16 07:47 UTC, tpetrina commented on src/server/api/routes/api-router.js
> +
Why is this here now?

2020-12-16 08:19 UTC, Deepti-Dk commented on src/server/api/routes/api-router.js
> +// const createEventRouter = require('./create-event.router');
Done

2020-12-16 08:19 UTC, Deepti-Dk commented on src/server/api/routes/api-router.js
> +
deleted it.

2020-12-16 08:32 UTC, Deepti-Dk commented on src/server/api/routes/api-router.js
> +// router.use('/createEvent', createEventRouter);
done

2020-12-16 16:44 UTC, yukafjaponesa approved these changes
looks nice.

2020-12-17 09:25 UTC, AkoAyukngat commented on src/server/api/controllers/events.controller.js
> +
this is smooth and clean :)

2020-12-17 09:32 UTC, AkoAyukngat commented on src/server/api/routes/events.router.js
> +
you well understood what you were doing.

2020-12-17 09:32 UTC, AkoAyukngat commented on src/server/api/controllers/events.controller.js
> +
this is smooth and clean :)

2020-12-17 11:00 UTC, tpetrina approved these changes

2020-12-17 11:29 UTC, merged