view modal for specific event
HackYourFuture-CPH/web-dev-rooms pull request #186
Opened 2020-12-15 20:59 UTC by MaherHussain

# Description

 this PR is about for view modal for specific event  , which show event details to admin  .

Fixes #129

# How to test?

tested in storybook and works fin 

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

2020-12-16 07:58 UTC, tpetrina requested changes

2020-12-16 07:58 UTC, tpetrina commented on src/client/containers/Admin-Event-details/Admin-Event-modal-view.js
> +  ];
Move this to props and then only use this list of students in Storybook.

2020-12-16 23:59 UTC, Yaser-Aldammad submitted a review, later dismissed
good job

2020-12-17 11:00 UTC, tpetrina requested changes

2020-12-17 11:00 UTC, tpetrina commented on src/client/containers/Admin-Event-details/Admin-Modal-View.stories.js
> +}
Why do you have this export in stories?

2020-12-19 09:11 UTC, tpetrina approved these changes

2020-12-19 09:55 UTC, Elia-Git approved these changes
Good job mate!

2020-12-19 09:55 UTC, merged