Modal View to EDIT an event that is not past
HackYourFuture-CPH/web-dev-rooms pull request #191
Opened 2020-12-17 10:38 UTC by nuha90

# Description

Modal View to EDIT an event that is not past

Fixes #134 

# Checklist

- [x] I have performed a self-review of my own code

2020-12-17 19:03 UTC, tpetrina requested changes
Please remove extra code.

2020-12-17 19:03 UTC, tpetrina commented on src/client/components/EditEventsModal/EditEventsModal.stories.js
> +};
Why create a new component inside a storybook file? This should not be here.

2020-12-18 07:44 UTC, MaherHussain commented on src/client/components/EditEventsModal/EditEventsModal.js
> +  link: PropTypes.string,
i think you need also to define onSubmit prop . "onSubmit:PropTypes.func,"

2020-12-19 09:15 UTC, tpetrina requested changes

2020-12-19 09:15 UTC, tpetrina commented on src/client/components/EditEventsModal/EditEventsModal.stories.js
> +};
You still have a component in story that is not needed. Why don't you move all this code under the `EditNotPastEvent` below?

2020-12-19 13:14 UTC, tpetrina approved these changes

2020-12-19 14:42 UTC, yukafjaponesa approved these changes

2020-12-19 14:42 UTC, merged