time zone component
HackYourFuture-CPH/web-dev-rooms pull request #212
Opened 2020-12-22 12:08 UTC by Yaser-Aldammad

# Description

Time zone component
Fixes #87 

# How to test?
storybook

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2020-12-22 17:38 UTC, MaherHussain approved these changes

2020-12-22 19:10 UTC, tpetrina requested changes

2020-12-22 19:10 UTC, tpetrina commented on src/client/components/TimeZone/TimeZone.stories.js
> +}
Why not put all this in the story below? No need for the extra function.

2020-12-22 19:10 UTC, tpetrina commented on src/client/components/TimeZone/TimeZone.component.js
> +  const [timeZone, setTimeZone] = useState('');
By doing this here, you prevent the consumer of this component from knowing which timezone was picked. You need to push these two through props.

2020-12-24 09:31 UTC, tpetrina approved these changes
Good stuff!

2020-12-24 10:50 UTC, nuha90 approved these changes

2020-12-24 10:50 UTC, merged