API:created endpoint to register student
HackYourFuture-CPH/web-dev-rooms pull request #227
Opened 2020-12-23 21:09 UTC by AkoAyukngat

# Description

This API is created to enable the registration of student.

Fixes #103

# How to test?

Swagger

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2020-12-24 09:38 UTC, tpetrina approved these changes
Looks good, looking forward to using it.

2020-12-24 09:40 UTC, tpetrina requested changes
Actually, I just realized that you are missing something! You need to also create a new entry in`user_roles` for the newly registered student. The role you should link against is student.

2020-12-28 08:21 UTC, tpetrina approved these changes

2020-12-28 08:21 UTC, tpetrina commented on src/server/api/controllers/user.controller.js
> +      return { successful: true };
In line 31 it is `success`. Don't you want these two to be exactly the same?

2020-12-29 23:57 UTC, MaherHussain approved these changes

2020-12-30 10:25 UTC, tpetrina approved these changes

2020-12-30 11:25 UTC, MaherHussain approved these changes

2020-12-30 11:25 UTC, merged