endpoint for registering mentor
HackYourFuture-CPH/web-dev-rooms pull request #228
Opened 2020-12-23 21:17 UTC by nuha90

# Description

create an endpoint for registering mentor

Fixes #216 

# How to test?

swagger and postman

# Checklist

- [x] I have performed a self-review of my own code

2020-12-24 09:41 UTC, tpetrina requested changes
Looks good, but I just realized you are missing a small piece. 
You need to also create a new entry in`user_roles` for the newly registered mentor. The role you should link against is mentor. See @AkoAyukngat and his PR, you both need to do similar thing.

2020-12-24 09:41 UTC, tpetrina commented on src/server/api/routes/mentor.router.js
> + *        description: Event created
Should be `Mentor registered`.

2020-12-28 08:22 UTC, tpetrina submitted a review, later dismissed

2020-12-28 08:22 UTC, tpetrina commented on src/server/api/controllers/mentor.controller.js
> +  const insertNewMentor = await knex('users').insert({
This should be `newMentorId`.

2020-12-28 08:22 UTC, tpetrina commented on src/server/api/controllers/mentor.controller.js
> +  const getMentorId = await knex('roles').where('name', 'mentor').first('id');
This should be named `mentorRole`.

2020-12-28 12:01 UTC, tpetrina approved these changes
Nice!

2020-12-28 12:41 UTC, claudion3 approved these changes

2020-12-28 12:42 UTC, merged