AppHeader CSS improvement
HackYourFuture-CPH/web-dev-rooms pull request #233
Opened 2020-12-26 14:50 UTC by Yaser-Aldammad

# Description
improve Appheader responsive CSS

Fixes #87 

# How to test?

storybook
# Checklist

- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2020-12-28 07:48 UTC, tpetrina requested changes

2020-12-28 07:48 UTC, tpetrina commented on src/client/components/Appheader/AppHeader.style.css
>    bottom: 25.42%;
While here, can you remove the absolute positioning and these 4 values? Instead, just use padding.

2020-12-28 07:48 UTC, tpetrina commented on src/client/components/Appheader/AppHeader.style.css
> +  background-size: contain;
Does this property make a difference?

2020-12-28 14:13 UTC, tpetrina commented on src/client/components/Appheader/AppHeader.style.css
> +  padding: 1% 0 1% 13%;
You should really switch away from percentages...

2020-12-28 14:13 UTC, tpetrina approved these changes

2020-12-29 08:26 UTC, tpetrina approved these changes

2020-12-29 19:54 UTC, MaherHussain approved these changes

2020-12-29 19:54 UTC, merged