Created a skill page and added a route
HackYourFuture-CPH/web-dev-rooms pull request #272
Opened 2021-01-04 02:31 UTC by AnilMula

# Description
This PR is to create a new skills page and adding  a route '/admin/skills'

Fixes #262 

# How to test?
Tested in local machine by running the project and giving the url in the browser http://localhost:3000/admin/skills

here is the test screenshot

![image](https://user-images.githubusercontent.com/60918335/103496130-5a4e8900-4e3d-11eb-9426-fa737ac298b9.png)

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

2021-01-04 08:35 UTC, tpetrina requested changes
Great start, just a little bit!

2021-01-04 08:35 UTC, tpetrina commented on src/client/App.js
> +        <Route exact path="/admin/skills">
Should be `AuthenticatedRoute`.

2021-01-04 08:35 UTC, tpetrina commented on src/client/containers/SkillsPage/SkillsPage.js
> +    axios.get('/api/skills').then((response) => {
Use `fetch` from #255.

2021-01-06 08:36 UTC, tpetrina submitted a review, later dismissed
Good stuff.

2021-01-07 19:57 UTC, tpetrina approved these changes
Looks good

2021-01-07 22:38 UTC, Elia-Git approved these changes
Good job!

2021-01-07 22:38 UTC, merged