EventsPage
HackYourFuture-CPH/web-dev-rooms pull request #275
Opened 2021-01-04 11:30 UTC by nuha90

# Description

events page

Fixes #266

2021-01-04 11:46 UTC, tpetrina requested changes
Good start.

2021-01-04 11:46 UTC, tpetrina commented on src/client/containers/EventsPage/EventsPage.js
> +    <>
You could use the `Layout` component here.

2021-01-04 11:46 UTC, tpetrina commented on src/client/containers/EventsPage/EventsPage.js
> +    fetch('/api/events').then((data) => {
To make things nicer, add `<Loader` while loading.

2021-01-04 11:46 UTC, tpetrina commented on src/client/containers/EventsPage/EventsPage.styles.css
> +  left: 50px;
Do not add `left` unless you are doing absolute positioning.

2021-01-04 11:46 UTC, tpetrina commented on src/client/containers/EventsPage/EventsPage.js
> +            <div className="events-page">
Don't you want this selector to be in the root element? To style the entire page, not just a single `div`?

2021-01-05 07:05 UTC, tpetrina commented on src/client/containers/EventsPage/EventsPage.js
> +      <Layout className="events-page">
If AppHeader is not inside Layout, how does it look like on the page?

2021-01-05 07:05 UTC, tpetrina commented on src/server/api/controllers/events.controller.js
> +        'description',
If you have time, you could fix these to properly format property names. it should be `eventType`, `eventDate`, etc.

Not necessary, just a nice thing to have.

2021-01-05 07:28 UTC, tpetrina approved these changes

2021-01-05 09:58 UTC, tpetrina approved these changes
🚀

2021-01-05 10:05 UTC, Pallabi-ghosh approved these changes

2021-01-05 10:06 UTC, merged