Register/cancel button for the event issue #268
HackYourFuture-CPH/web-dev-rooms pull request #280
Opened 2021-01-05 12:05 UTC by Pallabi-ghosh

# Description

Added Register/cancel Button for students
Fixes # (268)

# How to test?

I have tested it in Storybook.

# Checklist

- [X ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2021-01-05 13:08 UTC, Yaser-Aldammad submitted a review, later dismissed

2021-01-05 13:50 UTC, tpetrina requested changes
You have a typo - it's `cancel` not `cancle`.

2021-01-05 13:50 UTC, tpetrina commented on src/client/components/CancleButtonWithEventsStudyGroups/CancleButtonWithEventsStudyGroups.js
> +  children: '',
Default is `null` for `PropTypes.node`.

2021-01-05 18:26 UTC, tpetrina commented
You have it twice!
<img width="294" alt="image" src="https://user-images.githubusercontent.com/1407815/103684441-d951d780-4f8b-11eb-8243-1d81f73db695.png">

Also, this doesn't look like what it is supposed to look like.
<img width="325" alt="image" src="https://user-images.githubusercontent.com/1407815/103684479-ecfd3e00-4f8b-11eb-971f-92f9a5f891bc.png">

2021-01-07 19:58 UTC, tpetrina approved these changes
Looks good.

2021-01-08 08:29 UTC, nuha90 approved these changes

2021-01-08 08:30 UTC, merged