Student profile update added
HackYourFuture-CPH/web-dev-rooms pull request #294
Opened 2021-01-18 13:19 UTC by Elia-Git

# Description

Please provide a short summary explaining what this PR is about.

Fixes #254 

# How to test?

Please provide a short summary of how your changes can be tested?

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

2021-01-18 15:23 UTC, tpetrina requested changes
Looks good, but with one small issue. Have you tested it works?

2021-01-18 15:23 UTC, tpetrina commented on src/server/api/routes/profile.router.js
> + *    summary: Update all students profile
What do you mean by word _all_ here?

2021-01-18 15:23 UTC, tpetrina commented on src/server/api/routes/profile.router.js
> +    .editProfile(req.user.id)
Did you forget to pass body here?

2021-01-19 18:07 UTC, Elia-Git commented on src/server/api/routes/profile.router.js
> +    .editProfile(req.user.id)
Typo

2021-01-19 18:07 UTC, Elia-Git commented on src/server/api/routes/profile.router.js
> +    .editProfile(req.user.id)
Fixed!

2021-01-19 18:07 UTC, Elia-Git commented on src/server/api/routes/profile.router.js
> + *    summary: Update all students profile
Typo!

2021-01-20 08:19 UTC, tpetrina approved these changes
Looks good!

2021-01-20 09:12 UTC, Pallabi-ghosh approved these changes

2021-01-20 09:12 UTC, merged