implement mentor profile
HackYourFuture-CPH/web-dev-rooms pull request #302
Opened 2021-01-19 17:47 UTC by claudion3

# Description

This PR is about Profile Endpoint For Mentor

Fixes #256 

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2021-01-19 20:52 UTC, tpetrina requested changes
It is a really good start, but you need to return the values mentioned in the issue.

2021-01-24 00:15 UTC, Elia-Git reviewed
The rest looks good ,just a small fix to get the values mentioned (Toni also mentioned).

2021-01-24 00:15 UTC, Elia-Git commented on src/server/api/controllers/profile.controller.js
> +};
This block of code needs to be removed
1. It wasn't  part of your issue
2.  was aimed to update a student's profile
3. is repeated below from line 65 to 84

2021-01-25 09:07 UTC, tpetrina requested changes
Good work, but you need to fix how you get skills for the mentor.

2021-01-25 09:07 UTC, tpetrina commented on src/server/api/controllers/profile.controller.js
> +        'skills.name as Skills',
Did you test this? I find it hard to believe that this is an array. You should probably get skills in a new knex call and you should return numbers:
> skills: array of numbers from mentor_skills table

Also, it should be named `skills` with lowercase `s`.

2021-02-06 18:33 UTC, AnilMula commented
hi Jean , can please push latest changes here

2021-02-06 19:18 UTC, tpetrina commented
Please remove changes to package.json and package-lock.json

2021-02-18 17:29 UTC, tpetrina approved these changes
Good job!

2021-02-18 17:29 UTC, merged