Storybook: Modal View with Title and closing button X #19
HackYourFuture-CPH/web-dev-rooms pull request #45
Opened 2020-11-17 11:46 UTC by 1620prabn

# Description

Modal view with title and closing X button created

Fixes # (19)

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2020-11-17 19:35 UTC, tpetrina requested changes

2020-11-17 19:35 UTC, tpetrina commented on src/client/components/Modal/Modal.css
> +* {
Global styles do not belong in a component CSS. Use a separate PR for that and adjust it in the global CSS.

2020-11-17 19:35 UTC, tpetrina commented on src/client/components/Modal/Modal.css
> +h4 {
This CSS selector isn't specific enough, please provide a better selector.

2020-11-17 19:37 UTC, tpetrina commented on src/client/components/Modal/Modal.js
> +    </div>
Consider also passing `children` property in this component.

2020-11-26 08:59 UTC, nuha90 commented
you made all the changes ,good work

2020-11-26 08:59 UTC, nuha90 submitted a review, later dismissed

2020-11-26 19:13 UTC, tpetrina requested changes
Great work, just a small step towards the end.

2020-11-26 19:13 UTC, tpetrina commented on src/client/components/Modal/Modal.js
> +  children: PropTypes.string.isRequired,
This should be `node`, not `string`.

2020-11-26 19:13 UTC, tpetrina commented on src/client/components/Modal/Modal.stories.js
> +export const FeedbackModal = () => <Modal title="Feedback Form" />;
If you specified `children` as required, why didn't you use it here?
Add it as an example.

2020-11-29 09:55 UTC, tpetrina approved these changes
Good work!

2020-11-29 11:15 UTC, Elia-Git approved these changes
Good job!

2020-11-29 11:15 UTC, merged