Storybook/migration
HackYourFuture-CPH/web-dev-rooms pull request #46
Opened 2020-11-17 14:27 UTC by Pallabi-ghosh

# Description

I have created the database table and I did it with Knex. Also, add a seed file for development to add a couple of initial groups.
I had a problem to understand this first but now its clear. 

Fixes # (issue)

# How to test?

This time there was no error for commit and push my branch. 

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2020-11-18 09:48 UTC, nuha90 commented
do you need date in your table pallabi ?

2020-11-18 11:12 UTC, tpetrina requested changes
Remove client side files.
Also, title of the PR is not clear, it should be “Migration and seed for groups”

2020-11-18 11:12 UTC, tpetrina commented on src/server/migrations/20201117134811_create_groups_schema.js
> +  return knex.schema.createTable('group_table', (table) => {
We don’t put `table` in table names. `groups` is enough,

2020-11-18 11:12 UTC, tpetrina commented on src/server/migrations/20201117134811_create_groups_schema.js
> +    table.datetime('startDate').notNullable();
Do we need groups to have start/end date? What would be the start/end date for group `class 14`?
These are not study groups but groups a student belongs to.

2020-11-24 09:02 UTC, Pallabi-ghosh commented
I have removed those client side file also change the PR name. Could you please take a look and approve this PR.

2020-11-24 21:10 UTC, closed without merging

2020-11-24 21:11 UTC, Pallabi-ghosh commented
Closing the PR because of too many commits.