Added Title and text card issue #15
HackYourFuture-CPH/web-dev-rooms pull request #53
Opened 2020-11-19 13:15 UTC by Kiran-Serolla

# Description

This PR is to create a storybook card  with Title and Text .

Fixes # 15

# How to test?
it is tested in storybook and is working **http://localhost:6007/?path=/story/title-and-text-card--component**

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

2020-11-26 09:16 UTC, Pallabi-ghosh submitted a review, later dismissed

2020-11-26 19:19 UTC, tpetrina requested changes
Just touch CSS a bit and you are good to go!

2020-11-26 19:19 UTC, tpetrina commented on src/client/components/Card/Card.styles.css
> +  position: absolute;
Are you sure you need `absolute` positioning? Seeps a bit off.

2020-11-26 19:19 UTC, tpetrina commented on src/client/components/Card/Card.styles.css
> +  width: 282px;
Not sure that we want to specify exact width. Are you sure? Have you tested on all screen sizes? Remove and we will later add it if needed.

2020-11-30 21:01 UTC, Pallabi-ghosh approved these changes

2020-12-01 17:22 UTC, tpetrina approved these changes
Good work!

2020-12-01 17:50 UTC, merged