Db migration modules
HackYourFuture-CPH/web-dev-rooms pull request #69
Opened 2020-11-23 12:11 UTC by yukafjaponesa

# Description

Databases: Create Migrations for Modules, topic yellow.

Fixes #63 

# How to test?

in text editor.

# Checklist

- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2020-11-25 09:51 UTC, dpfernandes requested changes
deleted_at should be null.

This field is used to validate if the record inserted was deleted or not. The logic behind is if deleted_at has a date it's because that same record was deleted on that same date.

Check this article for more info https://medium.com/galvanize/soft-deletion-is-actually-pretty-hard-cb434e24825c

2020-11-26 07:59 UTC, dpfernandes commented
If this PR has 4 migrations files for 4 different tables why do you call it **Db migration modules** ?

2020-11-26 08:00 UTC, dpfernandes commented
Also the description of the PR only mentions Modules when you have 3 tables more. Why is that?

2020-11-26 11:07 UTC, 1620prabn commented
> If this PR has 4 migrations files for 4 different tables why do you call it **Db migration modules** ?

titile is changed

2020-11-26 20:01 UTC, tpetrina requested changes
I am a bit disappointed in this not working at all. You must try running the code or asking for help if it doesn't work.

2020-11-26 20:01 UTC, tpetrina commented on src/server/migrations/20201125222522_create_questions_table.js
> +      .references('id')
Missing `.unsigned()` before `references`.

2020-11-26 20:01 UTC, tpetrina commented on src/server/migrations/20201125222522_create_questions_table.js
> +      .references('id')
Missing `.unsigned()` before `references`.

2020-11-26 20:01 UTC, tpetrina commented on src/server/migrations/20201125223036_create_feedback_table.js
> +      .references('id')
Missing `.unsigned()` before `references`.

2020-11-26 20:01 UTC, tpetrina commented on src/server/migrations/20201125223036_create_feedback_table.js
> +      .references('id')
Missing `.unsigned()` before `references`.

2020-11-26 20:01 UTC, tpetrina commented on src/server/migrations/20201125223036_create_feedback_table.js
> +      .references('id')
Missing `.unsigned()` before `references`.

2020-11-26 20:01 UTC, tpetrina commented
But to not sound too negative, this is a 90% great job. You were almost at the finish line! 👍

2020-11-30 20:00 UTC, Elia-Git commented on src/server/migrations/20201129173036_create_feedback_table.js
> +exports.up = function (knex) {
This table should be deleted also in the remote. You only deleted locally but not in the remote.

2020-11-30 20:10 UTC, Elia-Git commented on src/server/migrations/20201129223036_create_feedback_table.js
> +};
This table also needs to be deleted !

2020-11-30 20:10 UTC, Elia-Git commented on src/server/migrations/20201129173036_create_feedback_table.js
> +};
This table should be deleted also in the remote. You only deleted locally but not in the remote. 
As Questions table is created this time 20201129222522

2020-12-01 00:25 UTC, closed without merging